.TH "_nsp_def_auto_exposure_parameters" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nsp_def_auto_exposure_parameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_device_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_nsp_def_auto_exposure_parameters\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinitial_ss\fP"
.br
.ti -1c
.RI "int \fBmin_ss\fP"
.br
.ti -1c
.RI "int \fBmax_ss\fP"
.br
.ti -1c
.RI "int \fBtarget_dn_value\fP"
.br
.ti -1c
.RI "int \fBupper_dn_value\fP"
.br
.ti -1c
.RI "int \fBlower_dn_value\fP"
.br
.ti -1c
.RI "int \fBmean_upper_dn_value\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_nsp_def_auto_exposure_parameters::_nsp_def_auto_exposure_parameters ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _nsp_def_auto_exposure_parameters::init ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int _nsp_def_auto_exposure_parameters::initial_ss"

.SS "int _nsp_def_auto_exposure_parameters::lower_dn_value"

.SS "int _nsp_def_auto_exposure_parameters::max_ss"

.SS "int _nsp_def_auto_exposure_parameters::mean_upper_dn_value"

.SS "int _nsp_def_auto_exposure_parameters::min_ss"

.SS "int _nsp_def_auto_exposure_parameters::mode"

.SS "int _nsp_def_auto_exposure_parameters::target_dn_value"

.SS "int _nsp_def_auto_exposure_parameters::upper_dn_value"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
