.TH "_OOIrradDataFileInfo" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_OOIrradDataFileInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBTimestamp\fP"
.br
.ti -1c
.RI "std::string \fBSpectrometer\fP"
.br
.ti -1c
.RI "std::string \fBLamp_SN\fP"
.br
.ti -1c
.RI "int \fBInteg_Time\fP"
.br
.ti -1c
.RI "int \fBFrame_average\fP"
.br
.ti -1c
.RI "int \fBBoxcar\fP"
.br
.ti -1c
.RI "double \fBFiber_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int _OOIrradDataFileInfo::Boxcar"

.SS "double _OOIrradDataFileInfo::Fiber_size"

.SS "int _OOIrradDataFileInfo::Frame_average"

.SS "int _OOIrradDataFileInfo::Integ_Time"

.SS "std::string _OOIrradDataFileInfo::Lamp_SN"

.SS "std::string _OOIrradDataFileInfo::Spectrometer"

.SS "std::string _OOIrradDataFileInfo::Timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
