.TH "_SApolloData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SApolloData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SApolloData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "std::string \fBsensor_id\fP"
.br
.ti -1c
.RI "double \fBadc_range\fP"
.br
.ti -1c
.RI "double \fBshutter_speed\fP"
.br
.ti -1c
.RI "std::string \fBsequence_data_path\fP"
.br
.ti -1c
.RI "\fBSDoubleArray2D\fP \fBfilter_data\fP"
.br
.ti -1c
.RI "std::vector< double > \fBdark_noise\fP"
.br
.ti -1c
.RI "std::vector< double > \fBwavelength\fP"
.br
.ti -1c
.RI "std::string \fBsource_type\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SApolloData::_SApolloData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SApolloData::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double _SApolloData::adc_range"

.SS "std::vector<double> _SApolloData::dark_noise"

.SS "std::string _SApolloData::date"

.SS "\fBSDoubleArray2D\fP _SApolloData::filter_data"

.SS "std::string _SApolloData::sensor_id"

.SS "std::string _SApolloData::sequence_data_path"

.SS "double _SApolloData::shutter_speed"

.SS "std::string _SApolloData::source_type"

.SS "std::vector<double> _SApolloData::wavelength"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
