.TH "_SDeviceInfo" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SDeviceInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SDeviceInfo\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBid\fP"
.br
.ti -1c
.RI "std::string \fBproduct_name\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.ti -1c
.RI "double \fBwavelength_begin\fP"
.br
.ti -1c
.RI "double \fBwavelength_end\fP"
.br
.ti -1c
.RI "double \fBwavelength_left\fP"
.br
.ti -1c
.RI "double \fBwavelength_right\fP"
.br
.ti -1c
.RI "double \fBresolution\fP"
.br
.ti -1c
.RI "int \fBaverage\fP"
.br
.ti -1c
.RI "int \fBboxcar\fP"
.br
.ti -1c
.RI "double \fBinteg_time\fP"
.br
.ti -1c
.RI "int \fBshutter_speed\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SDeviceInfo::_SDeviceInfo ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SDeviceInfo::reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int _SDeviceInfo::average"

.SS "int _SDeviceInfo::boxcar"

.SS "std::string _SDeviceInfo::id"

.SS "double _SDeviceInfo::integ_time"

.SS "std::string _SDeviceInfo::product_name"

.SS "double _SDeviceInfo::resolution"

.SS "int _SDeviceInfo::shutter_speed"

.SS "std::string _SDeviceInfo::type"

.SS "double _SDeviceInfo::wavelength_begin"

.SS "double _SDeviceInfo::wavelength_end"

.SS "double _SDeviceInfo::wavelength_left"

.SS "double _SDeviceInfo::wavelength_right"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
