.TH "_SFilterDataCalibPerf" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SFilterDataCalibPerf
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SFilterDataCalibPerf\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmeasTime\fP"
.br
.ti -1c
.RI "std::string \fBsensor_id\fP"
.br
.ti -1c
.RI "std::string \fBsensor_type\fP"
.br
.ti -1c
.RI "std::string \fBdevice\fP"
.br
.ti -1c
.RI "int \fBAVERAGES\fP"
.br
.ti -1c
.RI "int \fBADC_RANGE_VAL\fP"
.br
.ti -1c
.RI "std::string \fBADC_GAIN\fP"
.br
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "std::vector< double > \fBmeasurand_filters\fP"
.br
.ti -1c
.RI "std::vector< double > \fBfilterout_raw_warmUp\fP"
.br
.ti -1c
.RI "int \fBintegration_DN_warmUp\fP"
.br
.ti -1c
.RI "double \fBexposure_time_warmUp\fP"
.br
.ti -1c
.RI "int \fBintegration_DN\fP"
.br
.ti -1c
.RI "double \fBexposure_time\fP"
.br
.ti -1c
.RI "int \fBintegration_DN_SS1\fP"
.br
.ti -1c
.RI "double \fBexposure_time_SS1\fP"
.br
.ti -1c
.RI "std::vector< double > \fBall_filter_out_raw\fP"
.br
.ti -1c
.RI "std::vector< double > \fBfilterout\fP"
.br
.ti -1c
.RI "std::vector< double > \fBfilterout_SS1\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SFilterDataCalibPerf::_SFilterDataCalibPerf ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SFilterDataCalibPerf::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string _SFilterDataCalibPerf::ADC_GAIN"

.SS "int _SFilterDataCalibPerf::ADC_RANGE_VAL"

.SS "std::vector<double> _SFilterDataCalibPerf::all_filter_out_raw"

.SS "int _SFilterDataCalibPerf::AVERAGES"

.SS "std::string _SFilterDataCalibPerf::date"

.SS "std::string _SFilterDataCalibPerf::device"

.SS "double _SFilterDataCalibPerf::exposure_time"

.SS "double _SFilterDataCalibPerf::exposure_time_SS1"

.SS "double _SFilterDataCalibPerf::exposure_time_warmUp"

.SS "std::vector<double> _SFilterDataCalibPerf::filterout"

.SS "std::vector<double> _SFilterDataCalibPerf::filterout_raw_warmUp"

.SS "std::vector<double> _SFilterDataCalibPerf::filterout_SS1"

.SS "int _SFilterDataCalibPerf::integration_DN"

.SS "int _SFilterDataCalibPerf::integration_DN_SS1"

.SS "int _SFilterDataCalibPerf::integration_DN_warmUp"

.SS "double _SFilterDataCalibPerf::measTime"

.SS "std::vector<double> _SFilterDataCalibPerf::measurand_filters"

.SS "std::string _SFilterDataCalibPerf::sensor_id"

.SS "std::string _SFilterDataCalibPerf::sensor_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
