.TH "_SModelConfigForSVM" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SModelConfigForSVM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SModelConfigForSVM\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsvm_type\fP"
.br
.ti -1c
.RI "int \fBkernel_type\fP"
.br
.ti -1c
.RI "int \fBdegree\fP"
.br
.ti -1c
.RI "double \fBNU\fP"
.br
.ti -1c
.RI "int \fBborder_length\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.ti -1c
.RI "double \fBsigma\fP"
.br
.ti -1c
.RI "double \fBP\fP"
.br
.ti -1c
.RI "double \fBgamma\fP"
.br
.ti -1c
.RI "double \fBprobability\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SModelConfigForSVM::_SModelConfigForSVM ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int _SModelConfigForSVM::border_length"

.SS "double _SModelConfigForSVM::C"

.SS "int _SModelConfigForSVM::degree"

.SS "double _SModelConfigForSVM::gamma"

.SS "int _SModelConfigForSVM::kernel_type"

.SS "double _SModelConfigForSVM::NU"

.SS "double _SModelConfigForSVM::P"

.SS "double _SModelConfigForSVM::probability"

.SS "double _SModelConfigForSVM::sigma"

.SS "int _SModelConfigForSVM::svm_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
