.TH "_SOL731Data" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SOL731Data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SOL731Data\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< double > \fBresolution\fP"
.br
.ti -1c
.RI "double \fBshutter_speed\fP"
.br
.ti -1c
.RI "std::vector< double > \fBfilter_data\fP"
.br
.ti -1c
.RI "std::string \fBfilter_device\fP"
.br
.ti -1c
.RI "double \fBsaturation\fP"
.br
.ti -1c
.RI "double \fBzero\fP"
.br
.ti -1c
.RI "std::vector< double > \fBfilter_data_wavelength\fP"
.br
.ti -1c
.RI "double \fBdark_noise\fP"
.br
.ti -1c
.RI "double \fBslit_size\fP"
.br
.ti -1c
.RI "std::string \fBcomments\fP"
.br
.ti -1c
.RI "std::string \fBlocation\fP"
.br
.ti -1c
.RI "double \fBversion\fP"
.br
.ti -1c
.RI "std::string \fBid\fP"
.br
.ti -1c
.RI "double \fBmonochromator_gain\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SOL731Data::_SOL731Data ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SOL731Data::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string _SOL731Data::comments"

.SS "double _SOL731Data::dark_noise"

.SS "std::vector<double> _SOL731Data::filter_data"

.SS "std::vector<double> _SOL731Data::filter_data_wavelength"

.SS "std::string _SOL731Data::filter_device"

.SS "std::string _SOL731Data::id"

.SS "std::string _SOL731Data::location"

.SS "double _SOL731Data::monochromator_gain"

.SS "std::vector<double> _SOL731Data::resolution"

.SS "double _SOL731Data::saturation"

.SS "double _SOL731Data::shutter_speed"

.SS "double _SOL731Data::slit_size"

.SS "double _SOL731Data::version"

.SS "double _SOL731Data::zero"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
