.TH "_SRefData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SRefData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SRefData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBstrCreatedDate\fP"
.br
.ti -1c
.RI "std::string \fBstrInstrument\fP"
.br
.ti -1c
.RI "int \fBiStartWL\fP"
.br
.ti -1c
.RI "int \fBiEndWL\fP"
.br
.ti -1c
.RI "int \fBiWLStep\fP"
.br
.ti -1c
.RI "std::vector< double > \fBSpectrumData\fP"
.br
.ti -1c
.RI "std::vector< int > \fBWavelengths\fP"
.br
.ti -1c
.RI "std::vector< int > \fBWavelengthList\fP"
.br
.ti -1c
.RI "std::vector< int > \fBBandwidthList\fP"
.br
.ti -1c
.RI "std::vector< int > \fBIntensityList\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SRefData::_SRefData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SRefData::reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<int> _SRefData::BandwidthList"

.SS "int _SRefData::iEndWL"

.SS "std::vector<int> _SRefData::IntensityList"

.SS "int _SRefData::iStartWL"

.SS "int _SRefData::iWLStep"

.SS "std::vector<double> _SRefData::SpectrumData"

.SS "std::string _SRefData::strCreatedDate"

.SS "std::string _SRefData::strInstrument"

.SS "std::vector<int> _SRefData::WavelengthList"

.SS "std::vector<int> _SRefData::Wavelengths"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
