.TH "_SSensorIDLocMapData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SSensorIDLocMapData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SSensorIDLocMapData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsystem\fP"
.br
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "int \fBnum_axis\fP"
.br
.ti -1c
.RI "std::vector< \fBSSensorLocInTray\fP > \fBsensor_loc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SSensorIDLocMapData::_SSensorIDLocMapData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SSensorIDLocMapData::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string _SSensorIDLocMapData::date"

.SS "int _SSensorIDLocMapData::num_axis"

.SS "std::vector<\fBSSensorLocInTray\fP> _SSensorIDLocMapData::sensor_loc"

.SS "std::string _SSensorIDLocMapData::system"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
