.TH "_SSensorTrayInfoData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SSensorTrayInfoData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SSensorTrayInfoData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "std::string \fBsystem\fP"
.br
.ti -1c
.RI "std::string \fBlocation\fP"
.br
.ti -1c
.RI "double \fBtotal_sensors\fP"
.br
.ti -1c
.RI "double \fBrows\fP"
.br
.ti -1c
.RI "double \fBcols\fP"
.br
.ti -1c
.RI "double \fBorig\fP"
.br
.ti -1c
.RI "double \fBrow_interval\fP"
.br
.ti -1c
.RI "double \fBcol_interval\fP"
.br
.ti -1c
.RI "double \fBthreshold\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsensor_pos\fP"
.br
.ti -1c
.RI "std::vector< double > \fBvalid_slots\fP"
.br
.ti -1c
.RI "std::vector< double > \fBsensor_order\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SSensorTrayInfoData::_SSensorTrayInfoData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SSensorTrayInfoData::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double _SSensorTrayInfoData::col_interval"

.SS "double _SSensorTrayInfoData::cols"

.SS "std::string _SSensorTrayInfoData::date"

.SS "std::string _SSensorTrayInfoData::location"

.SS "double _SSensorTrayInfoData::orig"

.SS "double _SSensorTrayInfoData::row_interval"

.SS "double _SSensorTrayInfoData::rows"

.SS "std::vector<double> _SSensorTrayInfoData::sensor_order"

.SS "std::vector<double> _SSensorTrayInfoData::sensor_pos"

.SS "std::string _SSensorTrayInfoData::system"

.SS "double _SSensorTrayInfoData::threshold"

.SS "double _SSensorTrayInfoData::total_sensors"

.SS "std::vector<double> _SSensorTrayInfoData::valid_slots"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
