.TH "_SSpectralData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SSpectralData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_SSpectralData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwavelength\fP"
.br
.ti -1c
.RI "std::vector< int > \fBdata\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_SSpectralData::_SSpectralData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _SSpectralData::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<int> _SSpectralData::data"

.SS "int _SSpectralData::wavelength"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
