.TH "_STitanPlan" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_STitanPlan
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_STitanPlan\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsensor_version\fP"
.br
.ti -1c
.RI "std::string \fBsensor_type\fP"
.br
.ti -1c
.RI "int \fBstart_wavelength\fP"
.br
.ti -1c
.RI "int \fBend_wavelength\fP"
.br
.ti -1c
.RI "int \fBstep_wavelength\fP"
.br
.ti -1c
.RI "int \fBadc_range\fP"
.br
.ti -1c
.RI "int \fBshutter_speed\fP"
.br
.ti -1c
.RI "int \fBframe_average\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_STitanPlan::_STitanPlan ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _STitanPlan::Reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int _STitanPlan::adc_range"

.SS "int _STitanPlan::end_wavelength"

.SS "int _STitanPlan::frame_average"

.SS "std::string _STitanPlan::sensor_type"

.SS "std::string _STitanPlan::sensor_version"

.SS "int _STitanPlan::shutter_speed"

.SS "int _STitanPlan::start_wavelength"

.SS "int _STitanPlan::step_wavelength"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
