.TH "_STraySettings" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_STraySettings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiLEDIntensity\fP"
.br
.ti -1c
.RI "int \fBiMatrixCol\fP"
.br
.ti -1c
.RI "int \fBiMatrixRow\fP"
.br
.ti -1c
.RI "double \fBiOrigX\fP"
.br
.ti -1c
.RI "double \fBiOrigY\fP"
.br
.ti -1c
.RI "double \fBiStepX\fP"
.br
.ti -1c
.RI "double \fBiStepY\fP"
.br
.ti -1c
.RI "int \fBiTestSS\fP"
.br
.ti -1c
.RI "int \fBiThresholdDN\fP"
.br
.ti -1c
.RI "double \fBiDistSensorToSensorX\fP"
.br
.ti -1c
.RI "double \fBiDistBoardToBoardX\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double _STraySettings::iDistBoardToBoardX"

.SS "double _STraySettings::iDistSensorToSensorX"

.SS "int _STraySettings::iLEDIntensity"

.SS "int _STraySettings::iMatrixCol"

.SS "int _STraySettings::iMatrixRow"

.SS "double _STraySettings::iOrigX"

.SS "double _STraySettings::iOrigY"

.SS "double _STraySettings::iStepX"

.SS "double _STraySettings::iStepY"

.SS "int _STraySettings::iTestSS"

.SS "int _STraySettings::iThresholdDN"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
