.TH "D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include Directory Reference" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbase\fP"
.br
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBdevice\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnsp_app_color_api\&.h\fP"
.br
.ti -1c
.RI "file \fBnsp_base_api\&.h\fP"
.br
.ti -1c
.RI "file \fBnsp_core_api\&.h\fP"
.br
.ti -1c
.RI "file \fBnsp_core_open_source_api\&.h\fP"
.br
.ti -1c
.RI "file \fBnsp_device_api\&.h\fP"
.br
.ti -1c
.RI "file \fBnsp_sdk_api\&.h\fP"
.br
.in -1c
