.TH "IntDataPair" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntDataPair \- Class definition for INT data pair of 'key' and 'val'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkey\fP"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class definition for INT data pair of 'key' and 'val'\&. 
.SH "Member Data Documentation"
.PP 
.SS "int IntDataPair::key"

.SS "int IntDataPair::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
