.TH "libusb_container_id_descriptor" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libusb_container_id_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbLength\fP"
.br
.ti -1c
.RI "uint8_t \fBbDescriptorType\fP"
.br
.ti -1c
.RI "uint8_t \fBbDevCapabilityType\fP"
.br
.ti -1c
.RI "uint8_t \fBbReserved\fP"
.br
.ti -1c
.RI "uint8_t \fBContainerID\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure representing the Container ID descriptor\&. This descriptor is documented in section 9\&.6\&.2\&.3 of the USB 3\&.0 specification\&. All multiple-byte fields, except UUIDs, are represented in host-endian format\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t libusb_container_id_descriptor::bDescriptorType"
Descriptor type\&. Will have value \fBlibusb_descriptor_type::LIBUSB_DT_DEVICE_CAPABILITY\fP LIBUSB_DT_DEVICE_CAPABILITY in this context\&. 
.SS "uint8_t libusb_container_id_descriptor::bDevCapabilityType"
Capability type\&. Will have value \fBlibusb_capability_type::LIBUSB_BT_CONTAINER_ID\fP LIBUSB_BT_CONTAINER_ID in this context\&. 
.SS "uint8_t libusb_container_id_descriptor::bLength"
Size of this descriptor (in bytes) 
.SS "uint8_t libusb_container_id_descriptor::bReserved"
Reserved field 
.SS "uint8_t libusb_container_id_descriptor::ContainerID[16]"
128 bit UUID 

.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
