.TH "libusb_ss_usb_device_capability_descriptor" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libusb_ss_usb_device_capability_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbLength\fP"
.br
.ti -1c
.RI "uint8_t \fBbDescriptorType\fP"
.br
.ti -1c
.RI "uint8_t \fBbDevCapabilityType\fP"
.br
.ti -1c
.RI "uint8_t \fBbmAttributes\fP"
.br
.ti -1c
.RI "uint16_t \fBwSpeedSupported\fP"
.br
.ti -1c
.RI "uint8_t \fBbFunctionalitySupport\fP"
.br
.ti -1c
.RI "uint8_t \fBbU1DevExitLat\fP"
.br
.ti -1c
.RI "uint16_t \fBbU2DevExitLat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure representing the SuperSpeed USB Device Capability descriptor This descriptor is documented in section 9\&.6\&.2\&.2 of the USB 3\&.0 specification\&. All multiple-byte fields are represented in host-endian format\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bDescriptorType"
Descriptor type\&. Will have value \fBlibusb_descriptor_type::LIBUSB_DT_DEVICE_CAPABILITY\fP LIBUSB_DT_DEVICE_CAPABILITY in this context\&. 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bDevCapabilityType"
Capability type\&. Will have value \fBlibusb_capability_type::LIBUSB_BT_SS_USB_DEVICE_CAPABILITY\fP LIBUSB_BT_SS_USB_DEVICE_CAPABILITY in this context\&. 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bFunctionalitySupport"
The lowest speed at which all the functionality supported by the device is available to the user\&. For example if the device supports all its functionality when connected at full speed and above then it sets this value to 1\&. 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bLength"
Size of this descriptor (in bytes) 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bmAttributes"
Bitmap encoding of supported device level features\&. A value of one in a bit location indicates a feature is supported; a value of zero indicates it is not supported\&. See \fBlibusb_ss_usb_device_capability_attributes\fP\&. 
.SS "uint8_t libusb_ss_usb_device_capability_descriptor::bU1DevExitLat"
U1 Device Exit Latency\&. 
.SS "uint16_t libusb_ss_usb_device_capability_descriptor::bU2DevExitLat"
U2 Device Exit Latency\&. 
.SS "uint16_t libusb_ss_usb_device_capability_descriptor::wSpeedSupported"
Bitmap encoding of the speed supported by this device when operating in SuperSpeed mode\&. See \fBlibusb_supported_speed\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
