.TH "D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include/device/nsp_device_interface_base.h" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include/device/nsp_device_interface_base.h
.SH SYNOPSIS
.br
.PP
\fC#include 'nsp_base_def\&.h'\fP
.br
\fC#include 'nsp_sdk_def\&.h'\fP
.br
\fC#include 'nsp_device_interface_stm_usb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsp_device_interface_base\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
