.TH "D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include/base/nsp_base_exceptions.h" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SVN/Prism_Light/trunk/NSP32_SDK/doc/include/base/nsp_base_exceptions.h
.SH SYNOPSIS
.br
.PP
\fC#include 'nsp_base_def\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnsp_base_exception\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBnsp_base_exception_message\fP (\fBNSP_ERROR_CODE\fP error_code)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* nsp_base_exception_message (\fBNSP_ERROR_CODE\fP error_code)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
