.TH "SChromaticity" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SChromaticity
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSChromaticity\fP ()"
.br
.ti -1c
.RI "\fBSChromaticity\fP (double x_, double y_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
 Struct definition for chromaticity(x, y) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SChromaticity::SChromaticity ()\fC [inline]\fP"

.SS "SChromaticity::SChromaticity (double x_, double y_)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double SChromaticity::x"

.SS "double SChromaticity::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
