.TH "SDataCollectPlan" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDataCollectPlan
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDataCollectPlan\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBss_start\fP"
.br
.ti -1c
.RI "int \fBss_end\fP"
.br
.ti -1c
.RI "int \fBss_step\fP"
.br
.ti -1c
.RI "int \fBaverage\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SDataCollectPlan::SDataCollectPlan ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int SDataCollectPlan::average"

.SS "int SDataCollectPlan::ss_end"

.SS "int SDataCollectPlan::ss_start"

.SS "int SDataCollectPlan::ss_step"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
