.TH "SDataProcessPlan" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDataProcessPlan
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDataProcessPlan\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuse_smooth\fP"
.br
.ti -1c
.RI "int \fBalgo_type\fP"
.br
.ti -1c
.RI "int \fBfunc_order\fP"
.br
.ti -1c
.RI "int \fBwindow_size\fP"
.br
.ti -1c
.RI "int \fBdata_type\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SDataProcessPlan::SDataProcessPlan ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int SDataProcessPlan::algo_type"

.SS "int SDataProcessPlan::data_type"

.SS "int SDataProcessPlan::func_order"

.SS "bool SDataProcessPlan::use_smooth"

.SS "int SDataProcessPlan::window_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
