.TH "SLCH" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLCH \- Struct definition for LCH color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBL\fP"
.br
.ti -1c
.RI "double \fBC\fP"
.br
.ti -1c
.RI "double \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct definition for LCH color space\&. 
.SH "Member Data Documentation"
.PP 
.SS "double SLCH::C"

.SS "double SLCH::h"

.SS "double SLCH::L"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
