.TH "SOneFilterData" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOneFilterData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_sdk_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSOneFilterData\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "std::vector< double > \fBraw\fP"
.br
.ti -1c
.RI "std::vector< double > \fBspec\fP"
.br
.ti -1c
.RI "\fBSDataAcqCondition\fP \fBcondition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SOneFilterData::SOneFilterData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP SOneFilterData::reset ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSDataAcqCondition\fP SOneFilterData::condition"

.SS "std::string SOneFilterData::date"

.SS "std::vector<double> SOneFilterData::raw"

.SS "std::vector<double> SOneFilterData::spec"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
