.TH "SRGBf" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRGBf \- Struct definition for DOUBLE-type rgb color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSRGBf\fP ()"
.br
.ti -1c
.RI "\fBSRGBf\fP (double r_, double g_, double b_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBg\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct definition for DOUBLE-type rgb color space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SRGBf::SRGBf ()\fC [inline]\fP"

.SS "SRGBf::SRGBf (double r_, double g_, double b_)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double SRGBf::b"

.SS "double SRGBf::g"

.SS "double SRGBf::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
