.TH "SxyY" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SxyY \- Struct definition for xyY color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSxyY\fP ()"
.br
.ti -1c
.RI "\fBSxyY\fP (double x_, double y_, double Y_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct definition for xyY color space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SxyY::SxyY ()\fC [inline]\fP"

.SS "SxyY::SxyY (double x_, double y_, double Y_)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double SxyY::x"

.SS "double SxyY::y"

.SS "double SxyY::Y"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
