.TH "SXYZ" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SXYZ \- Struct definition for XYZ color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSXYZ\fP ()"
.br
.ti -1c
.RI "\fBSXYZ\fP (double x_, double y_, double z_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct definition for XYZ color space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SXYZ::SXYZ ()\fC [inline]\fP"

.SS "SXYZ::SXYZ (double x_, double y_, double z_)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double SXYZ::x"

.SS "double SXYZ::y"

.SS "double SXYZ::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
