.TH "usb_ctrl_setup" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_ctrl_setup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbRequestType\fP"
.br
.ti -1c
.RI "unsigned char \fBbRequest\fP"
.br
.ti -1c
.RI "unsigned short \fBwValue\fP"
.br
.ti -1c
.RI "unsigned short \fBwIndex\fP"
.br
.ti -1c
.RI "unsigned short \fBwLength\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char usb_ctrl_setup::bRequest"

.SS "unsigned char usb_ctrl_setup::bRequestType"

.SS "unsigned short usb_ctrl_setup::wIndex"

.SS "unsigned short usb_ctrl_setup::wLength"

.SS "unsigned short usb_ctrl_setup::wValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
