.TH "usb_interface_descriptor" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_interface_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbLength\fP"
.br
.ti -1c
.RI "unsigned char \fBbDescriptorType\fP"
.br
.ti -1c
.RI "unsigned char \fBbInterfaceNumber\fP"
.br
.ti -1c
.RI "unsigned char \fBbAlternateSetting\fP"
.br
.ti -1c
.RI "unsigned char \fBbNumEndpoints\fP"
.br
.ti -1c
.RI "unsigned char \fBbInterfaceClass\fP"
.br
.ti -1c
.RI "unsigned char \fBbInterfaceSubClass\fP"
.br
.ti -1c
.RI "unsigned char \fBbInterfaceProtocol\fP"
.br
.ti -1c
.RI "unsigned char \fBiInterface\fP"
.br
.ti -1c
.RI "struct \fBusb_endpoint_descriptor\fP * \fBendpoint\fP"
.br
.ti -1c
.RI "unsigned char * \fBextra\fP"
.br
.ti -1c
.RI "int \fBextralen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char usb_interface_descriptor::bAlternateSetting"

.SS "unsigned char usb_interface_descriptor::bDescriptorType"

.SS "unsigned char usb_interface_descriptor::bInterfaceClass"

.SS "unsigned char usb_interface_descriptor::bInterfaceNumber"

.SS "unsigned char usb_interface_descriptor::bInterfaceProtocol"

.SS "unsigned char usb_interface_descriptor::bInterfaceSubClass"

.SS "unsigned char usb_interface_descriptor::bLength"

.SS "unsigned char usb_interface_descriptor::bNumEndpoints"

.SS "struct \fBusb_endpoint_descriptor\fP* usb_interface_descriptor::endpoint"

.SS "unsigned char* usb_interface_descriptor::extra"

.SS "int usb_interface_descriptor::extralen"

.SS "unsigned char usb_interface_descriptor::iInterface"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
