.TH "usb_endpoint_descriptor" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_endpoint_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbLength\fP"
.br
.ti -1c
.RI "unsigned char \fBbDescriptorType\fP"
.br
.ti -1c
.RI "unsigned char \fBbEndpointAddress\fP"
.br
.ti -1c
.RI "unsigned char \fBbmAttributes\fP"
.br
.ti -1c
.RI "unsigned short \fBwMaxPacketSize\fP"
.br
.ti -1c
.RI "unsigned char \fBbInterval\fP"
.br
.ti -1c
.RI "unsigned char \fBbRefresh\fP"
.br
.ti -1c
.RI "unsigned char \fBbSynchAddress\fP"
.br
.ti -1c
.RI "unsigned char * \fBextra\fP"
.br
.ti -1c
.RI "int \fBextralen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char usb_endpoint_descriptor::bDescriptorType"

.SS "unsigned char usb_endpoint_descriptor::bEndpointAddress"

.SS "unsigned char usb_endpoint_descriptor::bInterval"

.SS "unsigned char usb_endpoint_descriptor::bLength"

.SS "unsigned char usb_endpoint_descriptor::bmAttributes"

.SS "unsigned char usb_endpoint_descriptor::bRefresh"

.SS "unsigned char usb_endpoint_descriptor::bSynchAddress"

.SS "unsigned char* usb_endpoint_descriptor::extra"

.SS "int usb_endpoint_descriptor::extralen"

.SS "unsigned short usb_endpoint_descriptor::wMaxPacketSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
