.TH "usb_dev_handle" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_dev_handle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusbi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlibusb_device_handle\fP * \fBhandle\fP"
.br
.ti -1c
.RI "struct \fBusb_device\fP * \fBdevice\fP"
.br
.ti -1c
.RI "int \fBlast_claimed_interface\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBusb_device\fP* usb_dev_handle::device"

.SS "\fBlibusb_device_handle\fP* usb_dev_handle::handle"

.SS "int usb_dev_handle::last_claimed_interface"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
