.TH "usb_descriptor_header" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_descriptor_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbLength\fP"
.br
.ti -1c
.RI "unsigned char \fBbDescriptorType\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char usb_descriptor_header::bDescriptorType"

.SS "unsigned char usb_descriptor_header::bLength"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
