.TH "usb_interface" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBusb_interface_descriptor\fP * \fBaltsetting\fP"
.br
.ti -1c
.RI "int \fBnum_altsetting\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBusb_interface_descriptor\fP* usb_interface::altsetting"

.SS "int usb_interface::num_altsetting"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
