.TH "usb_device_descriptor" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usb_device_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lusb\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbLength\fP"
.br
.ti -1c
.RI "unsigned char \fBbDescriptorType\fP"
.br
.ti -1c
.RI "unsigned short \fBbcdUSB\fP"
.br
.ti -1c
.RI "unsigned char \fBbDeviceClass\fP"
.br
.ti -1c
.RI "unsigned char \fBbDeviceSubClass\fP"
.br
.ti -1c
.RI "unsigned char \fBbDeviceProtocol\fP"
.br
.ti -1c
.RI "unsigned char \fBbMaxPacketSize0\fP"
.br
.ti -1c
.RI "unsigned short \fBidVendor\fP"
.br
.ti -1c
.RI "unsigned short \fBidProduct\fP"
.br
.ti -1c
.RI "unsigned short \fBbcdDevice\fP"
.br
.ti -1c
.RI "unsigned char \fBiManufacturer\fP"
.br
.ti -1c
.RI "unsigned char \fBiProduct\fP"
.br
.ti -1c
.RI "unsigned char \fBiSerialNumber\fP"
.br
.ti -1c
.RI "unsigned char \fBbNumConfigurations\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned short usb_device_descriptor::bcdDevice"

.SS "unsigned short usb_device_descriptor::bcdUSB"

.SS "unsigned char usb_device_descriptor::bDescriptorType"

.SS "unsigned char usb_device_descriptor::bDeviceClass"

.SS "unsigned char usb_device_descriptor::bDeviceProtocol"

.SS "unsigned char usb_device_descriptor::bDeviceSubClass"

.SS "unsigned char usb_device_descriptor::bLength"

.SS "unsigned char usb_device_descriptor::bMaxPacketSize0"

.SS "unsigned char usb_device_descriptor::bNumConfigurations"

.SS "unsigned short usb_device_descriptor::idProduct"

.SS "unsigned short usb_device_descriptor::idVendor"

.SS "unsigned char usb_device_descriptor::iManufacturer"

.SS "unsigned char usb_device_descriptor::iProduct"

.SS "unsigned char usb_device_descriptor::iSerialNumber"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
