.TH "UsbDevId" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsbDevId
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_device_interface_stm_usb\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static map< int, int > \fBcreate_map\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static map< int, int > \fBcurrentDevId\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static map<int, int> UsbDevId::create_map ()\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "map<int, int> UsbDevId::currentDevId\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
