.TH "YUV" 3 "Tue Jan 31 2017" "Version v1.7" "NSP32 SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YUV \- Struct definition for \fBYUV\fP color space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nsp_base_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBu\fP"
.br
.ti -1c
.RI "float \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct definition for \fBYUV\fP color space\&. 
.SH "Member Data Documentation"
.PP 
.SS "float YUV::u"

.SS "float YUV::v"

.SS "float YUV::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for NSP32 SDK from the source code\&.
